### ISSUE TITLE
Add Message.system_content

### ISSUE THREAD

**Issue by CircuitSacul** [hikari-py/hikari#1035]
### Summary

Essentially, this would return Message.content for normal messages, but the content shown to a discord client for system messages (Such as "User joined the server").

### Why is this needed?

It would be very nice to have, rather than everyone who wants it figure out how to do it and then create a utility function for it.

### Ideal implementation

discord.py has an implementation which could be used with a bit of modification.
https://github.com/Rapptz/discord.py/blob/45d498c1b76deaf3b394d17ccf56112fa691d160/discord/message.py#L997

### Checklist

- [X] I have searched the issue tracker and have made sure it's not a duplicate. If it is a follow up of another issue, I have specified it.

**Comment by davfsa** [comment]
What those messages display is not documented anywhere and it is purely client implementation. Because of this, I don't think it would be nice to have in hikari, as we would just be hardcoding strings that could change at any time. Addtionally, a lot of those messages rely on cache info, which wont always be there

Instead, you could create your own utility function that fetches the correct information and renders it nicely for your use case :)

**Comment by CircuitSacul** [comment]
> What those messages display is not documented anywhere and it is purely client implementation. Because of this, I don't think it would be nice to have in hikari, as we would just be hardcoding strings that could change at any time. Addtionally, a lot of those messages rely on cache info, which wont always be there
> 
> Instead, you could create your own utility function that fetches the correct information and renders it nicely for your use case :)

I completely understand, I just thought I would ask anyways. Thanks.
