### ISSUE TITLE
Implement user DM flow for sending new messages.

### ISSUE THREAD

**Issue by ghost** [hikari-py/hikari#237]
> How do we DM users now then and respond to DMs?
> make two API calls per message we want to send to ensure the channel is open?

Yep sounds about right, right now this cache is gateway only and seeing as the events were removed from V8 there's no point in keeping any of this around as it'll always be empty

_Originally posted by @FasterSpeeding in https://github.com/nekokatt/hikari/pull/234#issuecomment-699677059_

**Comment by ahnaf-zamil** [comment]
So can you explain what the issue actually is? What do we want to do?

**Comment by nekokatt** [comment]
we want to send messages to users.

This may require one API call if you know the channel ID, or two if you dont.

**Comment by ahnaf-zamil** [comment]
how come we don't know the channel id? Won't the user specify the ID when they want to send a message? and if we don't have the channel ID, how do we get it?

**Comment by nekokatt** [comment]
@ahnaf-zamil how come we don't know the channel id? 

Because discord don't tell us anymore, v8 removed the event for it.

> Won't the user specify the ID when they want to send a message?

Sure, they can. Where are they going to find an arbitrarily generated snowflake from Discord's internal datastore though? :)

> and if we don't have the channel ID, how do we get it?

call the [create_dm_channel](https://nekokatt.github.io/hikari/hikari/api/rest.html#hikari.api.rest.RESTClient.create_dm_channel) endpoint first. Then call the [create_message](https://nekokatt.github.io/hikari/hikari/api/rest.html#hikari.api.rest.RESTClient.create_message) endpoint with that result for the channel.

**Comment by ahnaf-zamil** [comment]
So if we make this whole thing as a single function, is that it for this issue?

**Comment by davfsa** [comment]
We wanted to implement it in a nicer implementation. This should allow sending several messages to the same dm without having to execute both calls all the time. Something along the lines of this: 
```py
async with user.dm() as dm_channel:
    await dm_channel.send("hello")
    await dm_channel.send("hello again")

```

**Comment by nekokatt** [comment]
I'd probably implement dm() in the same way I did trigger_typing(), where it works in an async with or as an await, possibly.

**Comment by davfsa** [comment]
Yep, that was my idea
