### ISSUE TITLE
Pypy compatibility

### ISSUE THREAD

**Issue by YodaPY** [hikari-py/hikari#354]
### Summary
Make hikari pypy compatible, so bot developers can optimize their code.

### Problem
Speed of bots written in python

### Checklist
- [x] I have searched the issue tracker and have made sure it's not a duplicate.
      If it is a follow up of another issue, I have specified it.

**Comment by davfsa** [comment]
Currently this is not possible due to pypy not supporting python 3.8 and (between other features) [`:=`](https://foss.heptapod.net/pypy/pypy/-/issues/3228). So this wont be implemented any time soon.

I'm aware of the necessary speedups and will be trying to work on them when the library is done (probably some Cython extensions)
